# Generated by Django 4.0 on 2024-07-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='photo_profile',
        ),
    ]
