# Generated by Django 4.0 on 2024-08-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_departement_nom_dep_alter_role_nom_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='niv_permission',
        ),
    ]
