# Generated by Django 4.0 on 2024-08-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_role_niv_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='fonction_admin',
            field=models.CharField(default='Aucun', max_length=150),
        ),
    ]
