# Generated by Django 4.0 on 2024-08-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_admin_fonction_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='creer_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creer_client', to='main.compte'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='creer_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creer_contrat', to='main.compte'),
        ),
        migrations.AddField(
            model_name='departement',
            name='creer_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creer_departement', to='main.compte'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='creer_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creer_partenaire', to='main.compte'),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='creer_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creer_paie', to='main.compte'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='creer_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creer_salarie', to='main.compte'),
        ),
        migrations.DeleteModel(
            name='Rapport',
        ),
    ]
