# Generated by Django 4.0 on 2024-08-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_role_acce_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_article', models.CharField(max_length=200)),
                ('detail_article', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_contrat', models.CharField(max_length=200)),
                ('soustitre_contrat', models.CharField(max_length=200)),
                ('text_intro_contrat', models.TextField(blank=True, null=True)),
                ('detail_contrat', models.TextField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contrat')),
            ],
        ),
        migrations.RenameField(
            model_name='fichedepaie',
            old_name='total_indemnite',
            new_name='indemnite_depl',
        ),
        migrations.RenameField(
            model_name='fichedepaie',
            old_name='total_prime',
            new_name='prime_ancienne',
        ),
        migrations.RenameField(
            model_name='fichedepaie',
            old_name='total_retenue',
            new_name='prime_panier',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='secteurActivite',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='site_web',
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='prime_salarie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='retenue_amu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='retenue_css',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Clause',
        ),
        migrations.AddField(
            model_name='article',
            name='doc_contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doc_contrat'),
        ),
    ]
