# Generated by Django 4.0 on 2024-08-09 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_article_doc_contrat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichedepaie',
            name='dateEmission',
        ),
        migrations.AddField(
            model_name='client',
            name='association_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('client_simple', 'Client Simple'), ('client_liee_entreprise', 'Client Liée à une entreprise')], default='client_simple', max_length=50),
        ),
        migrations.AddField(
            model_name='compte',
            name='date_creer',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contrat',
            name='fait_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='demandeemploye',
            name='fait_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='type_entreprise',
            field=models.CharField(blank=True, choices=[('mon_entreprise', 'Mon Entreprise'), ('entreprise_partenaire', 'Entreprise Partenaire')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaie',
            name='fait_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='entreprise_affilier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.entreprise'),
        ),
    ]
