# Generated by Django 4.0 on 2024-08-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_affectation_contratsalarie_demandesalarie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
