# Generated by Django 4.0 on 2024-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_entreprise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='site_web',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
