# Generated by Django 4.0 on 2024-08-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_contrat_delai_alerte_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='entreprise_simple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.entreprise'),
        ),
    ]
