# Generated by Django 4.0 on 2024-08-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_departement_est_active_entreprise_est_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnregistrerPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contrat')),
            ],
        ),
    ]
