# Generated by Django 4.0 on 2024-08-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_enregistrerpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichedepaieaffectation',
            name='indemnite_depl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaieaffectation',
            name='prime_salissure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
