# Generated by Django 4.0 on 2024-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_fichedepaieaffectation_indemnite_depl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichedepaieaffectation',
            old_name='montant',
            new_name='montant_de_base',
        ),
        migrations.AddField(
            model_name='fichedepaieaffectation',
            name='montant_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
