# Generated by Django 4.0 on 2024-08-28 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_montant_fichedepaieaffectation_montant_de_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrerpdf',
            name='fiche_de_paie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fichedepaiesalarie'),
        ),
        migrations.AddField(
            model_name='enregistrerpdf',
            name='fiche_de_paie_affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fichedepaieaffectation'),
        ),
        migrations.AlterField(
            model_name='enregistrerpdf',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contrat'),
        ),
    ]
