# Generated by Django 4.0 on 2024-08-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_enregistrerpdf_fiche_de_paie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichedepaieaffectation',
            name='heure_supp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaieaffectation',
            name='heure_travail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaieaffectation',
            name='nbre_jour_travail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaieaffectation',
            name='taux_heure_supp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichedepaieaffectation',
            name='taux_heure_travail',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
